### ISSUE TITLE
UI и PP

### ISSUE THREAD

**Issue by FanManutd** [DmitryGuseatnicov/Toxin-Hotel-MetaLamp#7]
1. Будет удобней, если кликабельная область будет стрелочка и текст вместе. Сейчас список разворачивается только по стрелочке.
2. Стрелка не должна выделяться при частых кликах. 
![2](https://user-images.githubusercontent.com/90761929/179237199-67044a42-e2fd-4c21-99b0-bb6eb43ce683.gif)

3. Здесь со стрелкой та же история. Общее правило такое - кликабельные элементы не должны попадать в выделение.
![image](https://user-images.githubusercontent.com/90761929/179237622-d6bdab47-73f9-426e-afe7-ed41cc4a904c.png)

4. Какие-то у тебя странные шрифты, не находишь? Ты уверен, что у тебя отображается именно Montserrat? 1й скрин - твой сайт, 2й - макет. 
![image](https://user-images.githubusercontent.com/90761929/179243774-7cfb6bc0-4b1f-406a-aec7-b8670cf18b4b.png)
![image](https://user-images.githubusercontent.com/90761929/179243783-6de35676-ab12-4b5c-bef1-0eadc66da5b2.png)

5. Сильно расходится Pixel Perfect, проверь пожалуйста на всех страницах
![image](https://user-images.githubusercontent.com/90761929/179244452-ea3c3cbd-0fff-43d1-b86e-8885808e3ece.png)

**Comment by DmitryGuseatnicov** [comment]
Из шрифтов там вроде точно Montserrat. качал его с  google fonts. проблема как оказалось была в font-size для элементов календаря )))

**Comment by FanManutd** [comment]
Странное поведение. Как буд-то единичка в конце при фокусе появляется. 
![2](https://user-images.githubusercontent.com/90761929/179757251-322f78a3-645a-408b-b7ed-eb4c9a088388.gif)
