### ISSUE TITLE
PUG

### ISSUE THREAD

**Issue by FanManutd** [DmitryGuseatnicov/Toxin-Hotel-MetaLamp#9]
Переменная которая нигде не используется? Такого не должно быть в проекте. Так же у тега `button` атрибут `type` по умолчанию равен `submit`, что может привести к неожиданному поведению, отправке формы по клику на кнопку, которая ничего отправлять не должна. Надо явно указывать атрибут `type`, что бы избегать подобных ситуаций.
![image](https://user-images.githubusercontent.com/90761929/179239202-f9ca55ca-5414-4c7d-81d6-7df5cbb38678.png)

**Comment by DmitryGuseatnicov** [comment]
на самом деле переменная submit должна была использоваться, чтобы как раз избежать случайной отправки формы, так как в форме бывает несколько кнопок и хотелось просто не указывать всем type, а только той что должна сабмитить форму,  но я проглядел этот момент и не указал ее в атрибутах )))). сейчас решил что наверное это лучше делать явно, а не по умолчанию
